include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # 💅 코드 스타일
    prefer_single_quotes: true
    always_use_package_imports: true
    avoid_print: false
    prefer_final_locals: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    sort_constructors_first: true
    unnecessary_this: true

    # ⚙️ 안정성과 가독성
    use_key_in_widget_constructors: true
    avoid_returning_null_for_future: true
    cancel_subscriptions: true
    close_sinks: true
    avoid_init_to_null: true

    # 🧩 네이밍 및 구조
    library_private_types_in_public_api: false
    avoid_classes_with_only_static_members: false
    constant_identifier_names: false
    file_names: true

analyzer:
  errors:
    # 필요 시 경고/에러 레벨 조정
    avoid_print: info
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
